variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- buildAndDeployApkUnstable
- buildAndDeployApkStable
- buildAndDeployPlaystore

buildAndDeployApkUnstable:
  stage: buildAndDeployApkUnstable
  script:
    - sh deploy-unstable.sh
  only:
    - tags
  except:
    - ^(dev)
  when: manual

buildAndDeployApkStable:
  stage: buildAndDeployApkStable
  script:
    - sh deploy-stable.sh
  only:
    - tags
  except:
    - branches
  when: manual

buildAndDeployPlaystore:
  stage: buildAndDeployPlaystore
  script:
    - sh deploy-playstore.sh
  only:
    - tags
  except:
    - branches
  when: manual
